services:

  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:26.7.2
    restart: always
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DB_HOST}:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - keycloak-db
    networks:
      - vartahub-network
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

  iam-db:
    image: postgres:18-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: iam
    networks:
      - vartahub-network
    volumes:
      - iam-db-data:/var/lib/postgresql
    restart: unless-stopped

  meeting-db:
    image: postgres:18-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: meeting
    networks:
      - vartahub-network
    volumes:
      - meeting-db-data:/var/lib/postgresql
    restart: unless-stopped

  keycloak-db:
    image: postgres:18-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: keycloak
    networks:
      - vartahub-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:8.10.1-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass vartahub --appendonly yes
    restart: unless-stopped

networks:
  vartahub-network:
    driver: bridge

volumes:
  iam-db-data:
  meeting-db-data:
  keycloak-db-data:
  redis-data: