spring:
  application:
    name: vartahub-iam-service

  datasource:
    url: jdbc:postgresql://localhost:5434/iam
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  server-url: http://localhost:8090
  realm: vartahub
  client-id: vartahub-iam-service

  config:
    admin-username: ${KEYCLOAK_ADMIN_USERNAME}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
    iam-client-secret: ${KEYCLOAK_IAM_CLIENT_SECRET}

    google-provider-client-id: ${GOOGLE_PROVIDER_CLIENT_ID}
    google-provider-client-secret: ${GOOGLE_PROVIDER_CLIENT_SECRET}

    smtp-host: ${SMTP_HOST}
    smtp-port: ${SMTP_PORT}
    smtp-user: ${SMTP_USER}
    smtp-password: ${SMTP_PASSWORD}

server:
  port: 9001