spring:
  application:
    name: vartahub-iam-service

  datasource:
    url: jdbc:postgresql://localhost:5434/iam
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  server-url: http://localhost:8090
  realm: vartahub
  client-id: vartahub
  client-secret: 1FubevGE7O5odFBztbjmDtX6BOWgzydO50lr5HcamIS1SYqVbIqMzh4wkLqt1yGkJH6ppg3cSQdBbvICYSWJsK

server:
  port: 9001